using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;

public class SceneTransitionManager : MonoBehaviour
{
    private static SceneTransitionManager instance;
    public static SceneTransitionManager Instance
    {
        get
        {
            if (instance == null)
            {
                instance = FindObjectOfType<SceneTransitionManager>();
                if (instance == null)
                {
                    GameObject go = new GameObject(nameof(SceneTransitionManager) + "_autogenerated");
                    instance = go.AddComponent<SceneTransitionManager>();
                    DontDestroyOnLoad(go);
                }
            }
            return instance;
        }
        private set => instance = value;
    }

    [SerializeField]
    private float _fadeInRate;

    [SerializeField]
    private float _fadeOutRate;

    [SerializeField]
    private Material _wipeMaterial;

    private static readonly int TransitionTime = Shader.PropertyToID("_Progress");

    private Coroutine _wipeCoroutine;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else if (instance != this)
        {
            Destroy(gameObject);
        }

        _wipeMaterial.SetFloat(TransitionTime, 1f);
        StartFadeout();
    }

    public void StartFadeout()
    {
        StartCoroutine(FadeOut());
    }

    [ContextMenu("Fade In")]
    public void StartFadein()
    {
        StartCoroutine(FadeIn());
    }

    private IEnumerator FadeOut()
    {
        float elapsedTime = 0f;
        while (elapsedTime <= 1f)
        {
            elapsedTime += Time.deltaTime / _fadeOutRate;
            _wipeMaterial.SetFloat(TransitionTime, elapsedTime);
            yield return null;
        }
    }

    private IEnumerator FadeIn()
    {
        float elapsedTime = 1f;
        while (elapsedTime > 0f)
        {
            elapsedTime -= Time.deltaTime / _fadeInRate;
            _wipeMaterial.SetFloat(TransitionTime, elapsedTime);
            yield return null;
        }
    }

    private IEnumerator LoadSceneAfterWipe(int sceneIndex)
    {
        yield return FadeIn();
        yield return SceneManager.LoadSceneAsync(sceneIndex);
        yield return FadeOut();
    }

    public void LoadScene(int sceneIndex)
    {
        StartCoroutine(LoadSceneAfterWipe(sceneIndex));
    }
    public void LoadScene(string sceneName)
    {
        StartCoroutine(LoadSceneAfterWipe(SceneManager.GetSceneByName(sceneName).buildIndex));
    }

    public void LoadNextScene()
    {
        StartCoroutine(LoadSceneAfterWipe(SceneManager.GetActiveScene().buildIndex + 1));
    }
}